name: Build Zygisk Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r22b # NDK version 22.0.7026061 is r22b

    - name: Build Zygisk Module
      run: |
        cd src/main/jni
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_ABI="armeabi-v7a arm64-v8a" APP_PLATFORM=android-21

    - name: Upload ARM64-v8a Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-module-arm64-v8a
        path: src/main/obj/local/arm64-v8a/libfoxcheats.so

    - name: Upload armeabi-v7a Artifact
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-module-armeabi-v7a
        path: src/main/obj/local/armeabi-v7a/libfoxcheats.so
